name: Test Suite

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
#  should_fail_test:
#    runs-on: ubuntu-latest
#    name: Should Fail Test
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Test deployment marker
#        uses: ./
#        with:
#          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
#          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
#          applicationId: 0
#          revision: "deployment-marker-action-should-fail-test:${{ github.ref }}"

  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test deployment marker
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_ENTITY_GUID }}
          version: "deployment-marker-action-basic-test:${{ github.ref }}"

  all_inputs_test:
    runs-on: ubuntu-latest
    name: All Inputs Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test deployment marker
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_ENTITY_GUID }}
          version: "deployment-marker-action-all-input-test-${{ github.sha }}"

          # Optional
          changelog: "See https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md for details"
          description: "Automated Deployment via Github Actions"
          region: ${{ secrets.NEW_RELIC_REGION }}
          user: "hardcoded-test-username"
